### ISSUE TITLE
is there any code about active learning?

### ISSUE THREAD

**Issue by yuxuanxu-pku** [zudi-lin/pytorch_connectomics#116]
hi i only find the code about clustering here. Is there any code about the active learning process？

**Comment by zudi-lin** [comment]
hi @yuxuanxu-pku, our previous VAE code for active learning was implemented in Tensorflow. I re-implemented it in PyTorch and you can check the project folder: https://github.com/zudi-lin/pytorch_connectomics/tree/master/projects/TwoStream
