### ISSUE TITLE
Bug: AttributeError when valid_mask is None

### ISSUE THREAD

**Issue by tinyalpha** [zudi-lin/pytorch_connectomics#126]
When `valid_mask=None` in VolumeDataset, the following code will throw `AttributeError: 'NoneType' object has no attribute 'copy'`.

https://github.com/zudi-lin/pytorch_connectomics/blob/fc4dff992702947854ce7c9fd549be1e2cb3711e/connectomics/data/utils/data_weight.py#L23

The following safer codes are suggested.

```python
  if mask is None:
      out[wid] = weight_binary_ratio(target.copy(), None, dilate)
  else:
      out[wid] = weight_binary_ratio(target.copy(), mask.copy(), dilate)
```

**Comment by zudi-lin** [comment]
Hi @tinyalpha, thanks for the bug report. Are you interested to submit a PR? My suggestion is to use
```python
out[wid] = weight_binary_ratio(target.copy(), None if mask is None else mask.copy(), dilate)
```

**Comment by tinyalpha** [comment]
Hi @zudi-lin, I have created a PR.
