### ISSUE TITLE
Unable to import connectomics.data.utils.relabel

### ISSUE THREAD

**Issue by PG-Gu** [zudi-lin/pytorch_connectomics#140]
Dear developers,

Hello!
I was trying a quick run of this tutorial notebook [pytorch_connectomics/notebooks/seg2affinity.ipynb](https://github.com/zudi-lin/pytorch_connectomics/blob/master/notebooks/seg2affinity.ipynb)
I encountered a problem that 
`ImportError: cannot import name 'relabel' from 'connectomics.data.utils'`
I wonder how could I add this function.
Thanks in advance.

**Comment by donglaiw** [comment]
The function name is changed to `reduce_label`. just updated the notebook.
