### ISSUE TITLE
test_augmentor does not support 2D models

### ISSUE THREAD

**Issue by donglaiw** [zudi-lin/pytorch_connectomics#55]
Need to extend test_augmentor to also support 2D models.
- data/augmentation/test_augmentor.py: add an attribute for the TestAugmentor object for 2D or 3D model
- engine/trainer.py: specify whether it's a 2D or 3D model

**Comment by zudi-lin** [comment]
Done: https://github.com/zudi-lin/pytorch_connectomics/blob/master/connectomics/data/augmentation/test_augmentor.py
