### ISSUE TITLE
the sample of 'im_train.json' in the yaml

### ISSUE THREAD

**Issue by Limingxing00** [zudi-lin/pytorch_connectomics#58]
hi，

thank you for the impressive work！I am concerned about the format that should be followed in the json file

Could you give an official sample of it？

**Comment by zudi-lin** [comment]
hi @Limingxing00 ,

I have updated the MitoEM page with more descriptions about using the JSON files:
https://github.com/zudi-lin/pytorch_connectomics/tree/master/configs/MitoEM

Examples are:
-  **im_train.json**: https://raw.githubusercontent.com/zudi-lin/pytorch_connectomics/master/configs/MitoEM/im_train.json
- **mito_train.json**: https://raw.githubusercontent.com/zudi-lin/pytorch_connectomics/master/configs/MitoEM/mito_train.json

Thank you for your interest in our work!

Zudi
