### ISSUE TITLE
Data loader bug

### ISSUE THREAD

**Issue by Limingxing00** [zudi-lin/pytorch_connectomics#60]
Hi,

when I load the MitoEM dataset, I meet an error "IndexError: index 1 is out of bounds for axis 2 with size 1".

data_io.py
---
```python
def vast2Seg(seg):
    # convert to 24 bits
    if seg.ndim==2:
        return seg
    else: #vast: rgb
        return seg[:,:,0].astype(np.uint32)*65536+seg[:,:,1].astype(np.uint32)*256+seg[:,:,2].astype(np.uint32)  # error!!
```

I find the shape of "seg" is  (2859, 2859, 1).  Because the labels of the MitoEM dataset are grey image. It seems that you haven't considered the case where the label is a grayscale image?

**Comment by zudi-lin** [comment]
hi @Limingxing00,

Could you show me more information about how to reproduce the error message? We handle gray scale images as 2D arrays, so the size should be just (2859, 2859).

**Comment by donglaiw** [comment]
@Limingxing00 Thanks for the bug report. Just fixed this with an additional check of the input image shape
