### ISSUE TITLE
Data augmentation documentation link is not working.

### ISSUE THREAD

**Issue by atul-77** [zudi-lin/pytorch_connectomics#67]
The following link for the documentation of data augmentation does not work:
https://zudi-lin.github.io/pytorch_connectomics/build/html/modules/augmentation.html

**Comment by zudi-lin** [comment]
Thank you for the bug report. The documentation of data augmentation is moved to: https://zudi-lin.github.io/pytorch_connectomics/build/html/modules/data.html#module-connectomics.data.augmentation.
