### ISSUE TITLE
Unsupervised or Semi-supervised learning

### ISSUE THREAD

**Issue by liyun-lu** [zudi-lin/pytorch_connectomics#82]
Hello, how do I set up a configuration file for unsupervised learning?  
My settings are as follows: 
DATASET:
IMAGE_NAME: train.tif
LABEL_NAME: None
AUGMENTOR: 
ADDITIONAL_TARGETS_NAME: None 
ADDITIONAL_TARGETS_TYPE: None 
But there is a bug in the program during runtime.  The configuration files you give are all examples of supervised learning. Can you give examples of unsupervised or semi-supervised configuration files?  And how to write the configuration file is explained in detail in the official document?

**Comment by zudi-lin** [comment]
hello @liyun-lu, currently the unsupervised and semi-supervised learning functions are under development. we will let you know when they are supported.

**Comment by zudi-lin** [comment]
Hi @liyun-lu, please check our technical report (https://arxiv.org/abs/2112.05754) for the use case of self-training (a type of semi-supervised learning) in Section 5.1. More functionalities will be provided.
