### ISSUE TITLE
Keyerror 'seg' in demo 'segmentation.ipynb'

### ISSUE THREAD

**Issue by HoraceKem** [zudi-lin/pytorch_connectomics#9]
**Describe the bug**
Following the demo 'segmentation.ipynb', there will be keyerror 'seg' in paragraph 4.

**Screenshots**
![Screenshot from 2019-07-02 08-47-52](https://user-images.githubusercontent.com/46670068/60474692-1d349400-9ca6-11e9-9034-baa4a83cc31c.png)

**System Specifications**
**Desktop (please complete the following information):**
- Operating system: Ubuntu 18.04LTS
- CUDA version: 10.0
- python version: 3.6
- pytorch version: 1.1.0
- Anything else that seems relevant: 
zwatershed version:1e8528c commit

**Comment by zudi-lin** [comment]
Hi @HoraceKem, thanks for report the error message. I have tested the notebook again and no bug was found. I noticed that for the Cython script in the *zwatershed* package there is a dict `map_init` created using the affinity volume. I guess the problem is related to the inputs. Could you please check that:
1. In **code block 3**, check that `aff` is of shape (3,z,y,x)? For SNEMI, the size should be (3,100,1024,1024).
2. In **code block 3**, check the `dtype` of `aff` is np.float32 and the data range is (0,1)?

**Comment by HoraceKem** [comment]
Hi @zudi-lin ,thanks for your advice
> In code block 4, after aff = aff.astype(np.float32) / 255.0, (1) check that aff is of shape (3,z,y,x)? For SNEMI, the size should be (3,100,1024,1024); (2) check the dtype of aff is np.float32 and the data range is (0,1) 

It's a pity that all these parameters of the input are correct. :( 
Later, I skipped the 2D segmentation and tried 3D segmentation using _waterz_ both in notebook and terminal (by _evaluation.py_). The results are right so there's sth. wrong just with _zwatershed_ package.
I'm wondering if external environment has an effect on _zwatershed_ such as cython version.
By the way, when we do segmentation mission, is a pre-2D segmentation necessary? In another word, can I just use _waterz_ instead of _zwatershed_ ?

**Comment by zudi-lin** [comment]
Hi @HoraceKem, yes, just use the *waterz* package is good enough to generate the 3D segmentation. We were just testing if the performance can be improved by combining two packages. FYI, my cython version is 0.29.6, and the _zwatershed_ package was installed (after `git clone`) by running `pip install --editable .`

**Comment by HoraceKem** [comment]
Hi @zudi-lin , I created a new conda environment and rebuilt the dependencies using `conda install --yes --file requirement.txt`. The error message of _zwatershed_ disappeared but the python version was set to 2.7. 
Anyway, the notebook works well now and I have  a general understanding about EM segmentation.
Thanks for you patient help! :)

**Comment by zudi-lin** [comment]
Great! Thanks for helping us improve the repo.
