### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by Crystalqijing** [zudi-lin/pytorch_connectomics#90]
Hello, I'm interested in the pytorch_connectomics. So I try to learn it, however, I encounter a problem. 
In the notebook, the data you gave is some pictures in png format, but the code seems to require the .h5 format, which makes me fail when I try to run the code. 
Could you do me a favor?
Thank you!

**Comment by zudi-lin** [comment]
Hi @Crystalqijing, the PNG pictures in the notebooks are just the visualizations of function outputs. To run the notebooks you need a copy of the 3D volume data, which can be in `.h5` or `.tif` formation. We have a copy of the data on Google Drive (https://drive.google.com/drive/folders/1Qvm83HNumebVSd_B8QRsOO5qzb1kAtem?usp=sharing).
